const types = {
    REQUEST_RANDOM_QUOTE: 'REQUEST_RANDOM_QUOTE',
    RECEIVE_RANDOM_QUOTE: 'RECEIVE_RANDOM_QUOTE',
    //cooper s
    CHANGE_NAME: 'CHANGE_NAME',
    GET_CONTACTS: 'GET_CONTACTS',
    GET_CURRENT_PAGE: 'GET_CURRENT_PAGE',
    GET_LISTS: 'GET_LIST',
    GET_GROUPS: 'GET_GROUPS',
    GET_TASKS: 'GET_TASKS',
    CLOSE_PAGE: 'CLOSE_PAGE',
};

export default types;